---
# Configuration of the Cycloid stack
version: '4'
name: 'ansible-runner'
canonical: 'stack-ansible-runner'
description: |
  Enables you to execute an Ansible playbook. This stack includes a preconfigured pipeline for running a single Ansible playbook
keywords:
  - 'ansible-runner'
  - 'ansible-playbook'
  - 'ansible'
  - 'playbook'
author: 'Cycloid'
image: |
  https://raw.githubusercontent.com/cycloid-community-catalog/stack-ansible-runner/master/icon.png
technologies:
  - technology: ansible
    version: n/a

config:
  default:
    name: 'Default'
    description: 'Ansible runner'
    # Configuration of the CI pipeline
    pipeline:
      pipeline:
        path: 'pipeline/pipeline.yml'
      variables:
        path: 'pipeline/variables.sample.yml'
        destination: '($ .config_root $)/pipeline/variables.yml'
