# Configuration of the CI pipeline
name: 'ansible-runner'
canonical: 'stack-ansible-runner'
status: 'public'
description: 'Allow you to run an ansible playbook*.'
keywords:
  - 'ansible-runner'
  - 'ansible-playbook'
  - 'ansible'
  - 'playbook'
technologies:
  - technology: ansible
    version: n/a

author: 'Cycloid'
image: 'https://raw.githubusercontent.com/cycloid-community-catalog/stack-ansible-runner/master/icon.png'
type: 'stack'
config:
  # Configuration of the CI pipeline
  pipeline:
    pipeline:
      path: 'pipeline/pipeline.yml'
    variables:
      path: 'pipeline/variables.sample.yml'
