---
# Configuration of the Cycloid stack
name: 'ansible-runner'
canonical: 'stack-ansible-runner'
status: 'public'
description: |
  Allow you to run an Ansible playbook.
keywords:
  - 'ansible-runner'
  - 'ansible-playbook'
  - 'ansible'
  - 'playbook'
author: 'Cycloid'
image: |
  https://raw.githubusercontent.com/cycloid-community-catalog/stack-ansible-runner/master/icon.png
technologies:
  - technology: ansible
    version: n/a

config:
  # Configuration of the CI pipeline
  pipeline:
    pipeline:
      path: 'pipeline/pipeline.yml'
    variables:
      path: 'pipeline/variables.sample.yml'
      destination: '($ project $)/pipeline/variables-($ environment $).yml'
